# redeploy Vercel site when a file in `docs` changes
# using VERCEL_DEPLOY_HOOK environment variable

name: Deploy site
on:
  push:
    paths:
      - "docs/**"
    branches:
      - main

jobs:
  deploy:
    name: Deploy site
    runs-on: ubicloud-standard-2
    if: github.repository_owner == 'oven-sh'
    steps:
      - name: Trigger Vercel build
        run: curl ${{ secrets.VERCEL_DEPLOY_HOOK }}
