name: CI

permissions:
  contents: read
  statuses: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  trigger:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - id: ci
        name: Start CI
        uses: buildkite/trigger-pipeline-action@v2.2.0
        with:
          buildkite_api_access_token: ${{ secrets.BUILDKITE_TOKEN }}
          pipeline: "bun/sandbox"
          send_pull_request: true
