name: Lint

on:
  pull_request:
  workflow_dispatch:

env:
  BUN_VERSION: "1.1.38"
  OXLINT_VERSION: "0.15.0"

jobs:
  lint-js:
    name: "Lint JavaScript"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: ./.github/actions/setup-bun
        with:
          bun-version: ${{ env.BUN_VERSION }}
      - name: Setup Dependencies
        run: bun install --global oxlint@${{ env.OXLINT_VERSION }}
      - name: Lint
        run: bun lint --quiet --format github




