name: Update lshpack

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  check-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Check lshpack version
        id: check-version
        run: |
          CURRENT_VERSION=$(grep -oP 'LSHPACK_VERSION\s+\K\S+' cmake/targets/BuildLshpack.cmake)
          if [ -z "$CURRENT_VERSION" ]; then
            echo "Error: Could not find current version in BuildLshpack.cmake"
            exit 1
          fi
          echo "current=$CURRENT_VERSION" >> $GITHUB_OUTPUT

          LATEST_RELEASE=$(curl -sL https://api.github.com/repos/litespeedtech/ls-hpack/releases/latest)
          LATEST_TAG=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
          LATEST_SHA=$(curl -sL "https://api.github.com/repos/litespeedtech/ls-hpack/git/ref/tags/$LATEST_TAG" | jq -r '.object.sha')
          if [ -z "$LATEST_SHA" ]; then
            echo "Error: Could not fetch latest version from GitHub API"
            exit 1
          fi
          if [ ${#LATEST_SHA} -ne 40 ]; then
            echo "Error: Invalid SHA length"
            exit 1
          fi
          echo "latest=$LATEST_SHA" >> $GITHUB_OUTPUT
          echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Update version if needed
        if: success() && steps.check-version.outputs.current != steps.check-version.outputs.latest
        run: |
          sed -i "s/LSHPACK_VERSION\s\+[0-9a-f]\+/LSHPACK_VERSION ${{ steps.check-version.outputs.latest }}/" cmake/targets/BuildLshpack.cmake

      - name: Create Pull Request
        if: success() && steps.check-version.outputs.current != steps.check-version.outputs.latest
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          add-paths: |
            cmake/targets/BuildLshpack.cmake
          commit-message: "deps: update lshpack to ${{ steps.check-version.outputs.latest }}"
          title: "deps: update lshpack to ${{ steps.check-version.outputs.latest }}"
          delete-branch: true
          branch: deps/update-lshpack-${{ steps.check-version.outputs.latest }}
          body: |
            ## What does this PR do?

            Updates lshpack to version ${{ steps.check-version.outputs.tag }}

            Auto-updated by [this workflow](https://github.com/oven-sh/bun/actions/workflows/update-lshpack.yml)